[package]
name = "learn_3"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
cfg-if = "1.0.4"
lazy_static = "1.5.0"
ouroboros = "0.18.5"
thiserror = "2.0.18"
thread_local = "1.1.9"
tokio = { version = "1.52.3", features = [
    "rt-multi-thread",
    "sync",
    "rt",
    "macros",
    "time"
] }
my_marco = { path = "../my_marco" }
futures = "0.3"