[package]
name = "adder"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = { git="https://github.com/rust-lang/regex" }

[target.'cfg(unix)'.dependencies]
openssl = { version=">0.1.0" }

[dev-dependencies]
pretty_assertions = "1"
criterion = "0.3"


[[bench]]
name = "my_benchmarks"
harness = false